### ISSUE TITLE
Crash after Play

### ISSUE THREAD

**Issue by Stay21** [skeskinen/UnrealMimic#1]
HI. I have written to you about a build problem.  The build is success but when i press play the project is crash.  When i press Play from VS ( Local Windows Debugger ) i get this information

https://postimg.org/image/xwv8lf7c7/

This is a video how do i build your project.
( the link will be work in 10min)
https://youtu.be/mfU9uiYBuoM

The plugin is importent to me so i hope you will help me.
Regards

**Comment by Stay21** [comment]
It seems like the problem is here:
https://s27.postimg.org/6u7wk8x9f/Capture.jpg

But i don't know how to fix it.
Can you help ?

**Comment by skeskinen** [comment]
It seems like opening the voice file fails inside the 3rd party library. 

Maybe the program doesn't have rights to open that file. Maybe try to place the voice file in your documents folder or something. 

You could also check console output in VS for error messages and try to place a breakpoint on `mimic_voice_load` line and press step (F11) until you hopefully see something useful.

**Comment by Stay21** [comment]
OK it works. 
I had damaged voice files. 
:)

**Comment by skeskinen** [comment]
EDIT: Ok, if it works just ignore this :)

Can you try the following steps for me:
1. Go to Plugins\UnrealMimic\Source\ThirdParty\Mimic
2. Delete lib and x64 folders
3. Open mimicDll.vcxproj
4. Build with the configuration you need, I think it's x64 and Debug
5. Try to rebuild & rerun the test project

I thought I had set up the build system to build the library but I guess didin't.

**Comment by Stay21** [comment]
No No. 
Your YouTube tutorial was good. 

My correct steps:
1. Download your repo 
https://s29.postimg.org/52mlq20bb/image.jpg
2. Download Mimic repo
https://s23.postimg.org/ealom1mor/image.jpg
3. Unzip and open your repo from UnrealMimic.uproject 
4. Click Yes to rebuild.
5. Unzip Memic Repo and import any voice form mimic-master\mimic-master\voices folder to the project.
6. In LevelBlueprint Connect pins and select reference to mimic voice variable

Should works :)
