### ISSUE TITLE
Cannot build it for 4.15.0

### ISSUE THREAD

**Issue by mrday86** [skeskinen/UnrealMimic#2]
Hello,
I cannot build it for unreal engine 4.15, it's possbile to fix it if you have time? Thanks

**Comment by skeskinen** [comment]
Sorry about slow response, I wasn't watching this repo for some reason.

Anyways I managed to get this to working again with 4.15.
I updated the sources, but you'll need to build it yourself.
Feel free to report back if you try this new version.
