### ISSUE TITLE
Mimic Voice object does not show up in search in editor

### ISSUE THREAD

**Issue by EntryGames** [skeskinen/UnrealMimic#4]
The demo download works but if you delete the object, it can't be added back.  See pic.

![voice](https://user-images.githubusercontent.com/5974556/31679903-9b091e60-b340-11e7-927a-7f3e9a43531c.png)

**Comment by skeskinen** [comment]
Mimic Voice is asset file that you can to add to the project like other assets (textures, models, etc.). You can download .flitevox files from here https://github.com/MycroftAI/mimic/tree/67e43bf0fa56008276b878ec3790aa5f32eb2a16/voices

**Comment by EntryGames** [comment]
what i mean is the Mimic Voice type it self, is not available.  Its available on the editor on the demo project, but when creating a new project, the voice type is inaccessible, the utube video show another object on the variable search. - see pic - 
![untitled-2](https://user-images.githubusercontent.com/5974556/31724470-c97ce560-b3ef-11e7-87df-b95fabcd304f.png)

**Comment by skeskinen** [comment]
Hmmm, apparently UnrealMimic is not marked as blueprint type. I pushed simple fix that should the problem, but don't have UE installed atm and the launcher keeps crashing so I can't test it or even try if it compiles.

**Comment by EntryGames** [comment]
Awesome, that works, thatnks
